### ISSUE TITLE
双击之后，界面没动静

### ISSUE THREAD

**Issue by zzzz438** [PeerXu/google-ip-explorer#7]
我找到exe，直接运行，没任何动静，删掉原来的output，等很长时间也没反映...
是那里的问题呢？

**Comment by PeerXu** [comment]
最近这些IP都被GFW封了...所以这个项目基本就悲剧了...

**Comment by zzzz438** [comment]
你的意思是，input这个文本的ip不行了嘛？
如果换更换里面的ip，程序还能用不？

**Comment by zzzz438** [comment]
因为我用go go tester 还是能找到些目前可用的ip的。
我觉得你的工具蛮好用的，想看下能怎样继续使用。

**Comment by PeerXu** [comment]
是的, input里面的IP已经不行, 能不能提供一下新的input列表呢?

**Comment by zzzz438** [comment]
nslookup -q=TXT _netblocks.google.com 8.8.8.8
我用这个命令的得到的ip段，还是能用go go tester扫到一些的。
http://www.somesky.net/thread-index-fid-6-tid-83.htm
这里面有很多方法，你看能不能把一些方法给工具化。

**Comment by PeerXu** [comment]
谢谢提供!
