### ISSUE TITLE
怎么不能找到可用IP了，记得很久之前都可以

### ISSUE THREAD

**Issue by k1995** [PeerXu/google-ip-explorer#8]

**Comment by PeerXu** [comment]
因为之前这批IP源被人曝光了, 然后GFW就封了... 如果有新的IP源范围请提供一下.. 谢谢

**Comment by k1995** [comment]
恩，我发现你程序有个小bug。你是根据判断响应码是200来判断是否可用，而我亲测一个Google IP后发现它会返回的是301（可能防止不正常访问，因为你没加User-Agent、Cookie）,从而导致你程序误判为不可用IP，而实际是可用的。

**Comment by PeerXu** [comment]
谢谢反馈, 我去看看.

**Comment by PeerXu** [comment]
@k1995 已经修改判断条件~
